//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxTreeList_v20_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxTreeList_v20_1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxTreeList_v20_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string ASPxTreeListStringId_Alt_Collapse {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Alt_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string ASPxTreeListStringId_Alt_DragAndDropHideColumnIcon {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Alt_DragAndDropHideColumnIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        internal static string ASPxTreeListStringId_Alt_Expand {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Alt_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string ASPxTreeListStringId_Alt_SortedAscending {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Alt_SortedAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string ASPxTreeListStringId_Alt_SortedDescending {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Alt_SortedDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ASPxTreeListStringId_CommandApplyFilter {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ASPxTreeListStringId_CommandCancel {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ASPxTreeListStringId_CommandClearFilter {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ASPxTreeListStringId_CommandDelete {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ASPxTreeListStringId_CommandEdit {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string ASPxTreeListStringId_CommandNew {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        internal static string ASPxTreeListStringId_CommandRecover {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string ASPxTreeListStringId_CommandUpdate {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CommandUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete?.
        /// </summary>
        internal static string ASPxTreeListStringId_ConfirmDelete {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to perform the action? All unsaved grid data will be lost..
        /// </summary>
        internal static string ASPxTreeListStringId_ConfirmOnLosingBatchChanges {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.ConfirmOnLosingBatchChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Chooser.
        /// </summary>
        internal static string ASPxTreeListStringId_CustomizationWindowCaption {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.CustomizationWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Form.
        /// </summary>
        internal static string ASPxTreeListStringId_PopupEditFormCaption {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.PopupEditFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node has descendant nodes..
        /// </summary>
        internal static string ASPxTreeListStringId_RecursiveDeleteError {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.RecursiveDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ASPxTreeListStringId_Toolbar_Cancel {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Toolbar_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        internal static string ASPxTreeListStringId_Toolbar_ClearFilter {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Toolbar_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Sorting.
        /// </summary>
        internal static string ASPxTreeListStringId_Toolbar_ClearSorting {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Toolbar_ClearSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string ASPxTreeListStringId_Toolbar_CollapseNode {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Toolbar_CollapseNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ASPxTreeListStringId_Toolbar_Delete {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Toolbar_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ASPxTreeListStringId_Toolbar_Edit {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Toolbar_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        internal static string ASPxTreeListStringId_Toolbar_ExpandNode {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Toolbar_ExpandNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to {0}.
        /// </summary>
        internal static string ASPxTreeListStringId_Toolbar_ExportTo {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Toolbar_ExportTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        internal static string ASPxTreeListStringId_Toolbar_FullCollapse {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Toolbar_FullCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        internal static string ASPxTreeListStringId_Toolbar_FullExpand {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Toolbar_FullExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string ASPxTreeListStringId_Toolbar_New {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Toolbar_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Root.
        /// </summary>
        internal static string ASPxTreeListStringId_Toolbar_NewRoot {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Toolbar_NewRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string ASPxTreeListStringId_Toolbar_Refresh {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Toolbar_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Chooser.
        /// </summary>
        internal static string ASPxTreeListStringId_Toolbar_ShowCustomizationWindow {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Toolbar_ShowCustomizationWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Row.
        /// </summary>
        internal static string ASPxTreeListStringId_Toolbar_ShowFilterRow {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Toolbar_ShowFilterRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Row Menu.
        /// </summary>
        internal static string ASPxTreeListStringId_Toolbar_ShowFilterRowMenu {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Toolbar_ShowFilterRowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer.
        /// </summary>
        internal static string ASPxTreeListStringId_Toolbar_ShowFooter {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Toolbar_ShowFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string ASPxTreeListStringId_Toolbar_Update {
            get {
                return ResourceManager.GetString("ASPxTreeListStringId.Toolbar_Update", resourceCulture);
            }
        }
    }
}
