//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxEditors_v20_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxEditors_v20_1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxEditors_v20_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ASPxEditorsStringId_BinaryImage_Cancel {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.BinaryImage_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ASPxEditorsStringId_BinaryImage_Clear {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.BinaryImage_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop image file here.
        /// </summary>
        internal static string ASPxEditorsStringId_BinaryImage_DropZone {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.BinaryImage_DropZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image.
        /// </summary>
        internal static string ASPxEditorsStringId_BinaryImage_Empty {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.BinaryImage_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid image data.
        /// </summary>
        internal static string ASPxEditorsStringId_BinaryImage_InvalidData {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.BinaryImage_InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File....
        /// </summary>
        internal static string ASPxEditorsStringId_BinaryImage_UploadFile {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.BinaryImage_UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        internal static string ASPxEditorsStringId_BinaryImage_Uploading {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.BinaryImage_Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_Cancel {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_Clear {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Days.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_FastNavBackToDays {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_FastNavBackToDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Months.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_FastNavBackToMonths {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_FastNavBackToMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Years.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_FastNavBackToYears {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_FastNavBackToYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_FastNavigation_HeaderBackAlt {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_FastNavigation_HeaderBackAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_FastNavigation_HeaderBackRtlAlt {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_FastNavigation_HeaderBackRtlAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_FastNavigation_NextPeriodAlt {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_FastNavigation_NextPeriodAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_FastNavigation_NextYearAlt {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_FastNavigation_NextYearAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_FastNavigation_PrevPeriodAlt {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_FastNavigation_PrevPeriodAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_FastNavigation_PrevYearAlt {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_FastNavigation_PrevYearAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next year.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_NextLargePeriodAlt {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_NextLargePeriodAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next month.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_NextMonthAlt {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_NextMonthAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_NextPeriodAlt {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_NextPeriodAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next year.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_NextYearAlt {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_NextYearAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_OK {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous year.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_PrevLargePeriodAlt {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_PrevLargePeriodAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous month.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_PrevMonthAlt {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_PrevMonthAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_PrevPeriodAlt {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_PrevPeriodAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous year.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_PrevYearAlt {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_PrevYearAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string ASPxEditorsStringId_Calendar_Today {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Calendar_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The submitted code is incorrect.
        /// </summary>
        internal static string ASPxEditorsStringId_Captcha_DefaultErrorText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Captcha_DefaultErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha image.
        /// </summary>
        internal static string ASPxEditorsStringId_Captcha_DefaultImageAlternateText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Captcha_DefaultImageAlternateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the code shown:.
        /// </summary>
        internal static string ASPxEditorsStringId_Captcha_DefaultTextBoxLabelText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Captcha_DefaultTextBoxLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show another code.
        /// </summary>
        internal static string ASPxEditorsStringId_Captcha_RefreshText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.Captcha_RefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        internal static string ASPxEditorsStringId_CheckBox_Checked {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.CheckBox_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unchecked.
        /// </summary>
        internal static string ASPxEditorsStringId_CheckBox_Unchecked {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.CheckBox_Unchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string ASPxEditorsStringId_CheckBox_Undefined {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.CheckBox_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Color.
        /// </summary>
        internal static string ASPxEditorsStringId_ColorEdit_AutomaticColor {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.ColorEdit_AutomaticColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ASPxEditorsStringId_ColorEdit_Cancel {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.ColorEdit_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Color....
        /// </summary>
        internal static string ASPxEditorsStringId_ColorEdit_CustomColor {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.ColorEdit_CustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Color.
        /// </summary>
        internal static string ASPxEditorsStringId_ColorEdit_ModalDropDownCaption {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.ColorEdit_ModalDropDownCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ASPxEditorsStringId_ColorEdit_OK {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.ColorEdit_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter strings must be at least {0} characters..
        /// </summary>
        internal static string ASPxEditorsStringId_ComboBox_FilterMinLengthText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.ComboBox_FilterMinLengthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to display..
        /// </summary>
        internal static string ASPxEditorsStringId_ComboBox_FilterNoResultsText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.ComboBox_FilterNoResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Value.
        /// </summary>
        internal static string ASPxEditorsStringId_ComboBox_ModalDropDownCaption {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.ComboBox_ModalDropDownCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Date.
        /// </summary>
        internal static string ASPxEditorsStringId_DateEdit_ModalDropDownCaption {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.DateEdit_ModalDropDownCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM/PM.
        /// </summary>
        internal static string ASPxEditorsStringId_DateEdit_ScrollPickerAmPmCaption {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.DateEdit_ScrollPickerAmPmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        internal static string ASPxEditorsStringId_DateEdit_ScrollPickerDaysCaption {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.DateEdit_ScrollPickerDaysCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        internal static string ASPxEditorsStringId_DateEdit_ScrollPickerHoursCaption {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.DateEdit_ScrollPickerHoursCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliseconds.
        /// </summary>
        internal static string ASPxEditorsStringId_DateEdit_ScrollPickerMillisecondsCaption {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.DateEdit_ScrollPickerMillisecondsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string ASPxEditorsStringId_DateEdit_ScrollPickerMinutesCaption {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.DateEdit_ScrollPickerMinutesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        internal static string ASPxEditorsStringId_DateEdit_ScrollPickerMonthsCaption {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.DateEdit_ScrollPickerMonthsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string ASPxEditorsStringId_DateEdit_ScrollPickerSecondsCaption {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.DateEdit_ScrollPickerSecondsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        internal static string ASPxEditorsStringId_DateEdit_ScrollPickerYearsCaption {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.DateEdit_ScrollPickerYearsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date range must be from {0} to {1} {2}.
        /// </summary>
        internal static string ASPxEditorsStringId_DateRangeErrorText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.DateRangeErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string ASPxEditorsStringId_DateRangeErrorTextDaysPlaceholder {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.DateRangeErrorTextDaysPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decades.
        /// </summary>
        internal static string ASPxEditorsStringId_DateRangeErrorTextDecadesPlaceholder {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.DateRangeErrorTextDecadesPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        internal static string ASPxEditorsStringId_DateRangeErrorTextMonthsPlaceholder {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.DateRangeErrorTextMonthsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        internal static string ASPxEditorsStringId_DateRangeErrorTextYearsPlaceholder {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.DateRangeErrorTextYearsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date range must be greater than or equal to {0} {1}.
        /// </summary>
        internal static string ASPxEditorsStringId_DateRangeMinErrorText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.DateRangeMinErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value.
        /// </summary>
        internal static string ASPxEditorsStringId_DefaultErrorText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.DefaultErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Condition.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_AddCondition {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_AddCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a new condition to this group.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_AddConditionHint {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_AddConditionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Group.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_AddGroup {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a new item to the list.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_AddValueHint {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_AddValueHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exists,Count,Max,Min,Avg,Sum.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_AggregateType {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_AggregateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_BetweenAnd {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_BetweenAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_Cancel {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals,Does not equal,Is greater than,Is greater than or equal to,Is less than,Is less than or equal to,Is between,Is not between,Contains,Does not contain,Begins with,Ends with,Is like,Is not like,Is blank,Is not blank,Is any of,Is none of,,,Is beyond this year,Is later this year,Is later this month,Is next week,Is later this week,Is tomorrow,Is today,Is yesterday,Is earlier this week,Is last week,Is earlier this month,Is earlier this year,Is prior this year.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_ClauseType {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_ClauseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_ClearFilter {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time operators.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_DateTimeOperatorMenuCaption {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_DateTimeOperatorMenuCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;empty&amp;gt;.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_Empty {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;lt;enter a value&amp;gt;.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_EmptyEnter {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_EmptyEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And,Or,Not And,Not Or.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_GroupType {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_GroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_Not {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_Not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_OK {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare to a value / another field&apos;s value.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_OperandTypeButtonHint {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_OperandTypeButtonHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Builder.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_PopupHeaderText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_PopupHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_Remove {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes this condition.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_RemoveConditionHint {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_RemoveConditionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Filter.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_ShowFilterControl {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_ShowFilterControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_TextFilterTabCaption {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_TextFilterTabCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual.
        /// </summary>
        internal static string ASPxEditorsStringId_FilterControl_VisualFilterTabCaption {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.FilterControl_VisualFilterTabCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date must be less than or equal to {0}.
        /// </summary>
        internal static string ASPxEditorsStringId_InvalidDateEditMaxDate {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.InvalidDateEditMaxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date must be greater than or equal to {0}.
        /// </summary>
        internal static string ASPxEditorsStringId_InvalidDateEditMinDate {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.InvalidDateEditMinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date must be in the range {0}...{1}.
        /// </summary>
        internal static string ASPxEditorsStringId_InvalidDateEditRange {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.InvalidDateEditRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be less than or equal to {0}.
        /// </summary>
        internal static string ASPxEditorsStringId_InvalidSpinEditMaxValue {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.InvalidSpinEditMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be greater than or equal to {0}.
        /// </summary>
        internal static string ASPxEditorsStringId_InvalidSpinEditMinValue {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.InvalidSpinEditMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number must be in the range {0}...{1}.
        /// </summary>
        internal static string ASPxEditorsStringId_InvalidSpinEditRange {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.InvalidSpinEditRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to filter....
        /// </summary>
        internal static string ASPxEditorsStringId_ListBoxFilteringEditorNullText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.ListBoxFilteringEditorNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string ASPxEditorsStringId_ListBoxSelectAllText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.ListBoxSelectAllText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expression validation failed.
        /// </summary>
        internal static string ASPxEditorsStringId_RegExValidationErrorText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.RegExValidationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string ASPxEditorsStringId_RequiredFieldErrorText {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.RequiredFieldErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Tokens.
        /// </summary>
        internal static string ASPxEditorsStringId_TokenBox_ModalDropDownCaption {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.TokenBox_ModalDropDownCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string ASPxEditorsStringId_TokenBox_TokenRemoveButtonToolTip {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.TokenBox_TokenRemoveButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrement.
        /// </summary>
        internal static string ASPxEditorsStringId_TrackBar_Decrement {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.TrackBar_Decrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag.
        /// </summary>
        internal static string ASPxEditorsStringId_TrackBar_Drag {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.TrackBar_Drag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment.
        /// </summary>
        internal static string ASPxEditorsStringId_TrackBar_Increment {
            get {
                return ResourceManager.GetString("ASPxEditorsStringId.TrackBar_Increment", resourceCulture);
            }
        }
    }
}
