//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxGantt_v20_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxGantt_v20_1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxGantt_v20_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ASPxGanttStringId_Add {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ASPxGanttStringId_CancelButton {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint violation.
        /// </summary>
        internal static string ASPxGanttStringId_ConstraintViolation {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.ConstraintViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ASPxGanttStringId_DeleteButton {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Dependency.
        /// </summary>
        internal static string ASPxGanttStringId_DeleteDependency {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.DeleteDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Task.
        /// </summary>
        internal static string ASPxGanttStringId_DeleteTask {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.DeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete a dependency from the task?.
        /// </summary>
        internal static string ASPxGanttStringId_DependencyDeleteConfirmation {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.DependencyDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do nothing.
        /// </summary>
        internal static string ASPxGanttStringId_DoNothing {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.DoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string ASPxGanttStringId_End {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep dependency and move.
        /// </summary>
        internal static string ASPxGanttStringId_KeepDependencyAndMove {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.KeepDependencyAndMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Resource Name.
        /// </summary>
        internal static string ASPxGanttStringId_NewResourceName {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.NewResourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Subtask.
        /// </summary>
        internal static string ASPxGanttStringId_NewSubtask {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.NewSubtask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Task.
        /// </summary>
        internal static string ASPxGanttStringId_NewTask {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.NewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ASPxGanttStringId_OkButton {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        internal static string ASPxGanttStringId_Progress {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q{0}.
        /// </summary>
        internal static string ASPxGanttStringId_QuarterAbbreviation {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.QuarterAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Manager.
        /// </summary>
        internal static string ASPxGanttStringId_ResourceManager {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.ResourceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        internal static string ASPxGanttStringId_Resources {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting a resource also removes it from tasks to which this resource is assigned.&lt;br /&gt;Are you sure you want to delete these resources?&lt;br /&gt;Resources: {0}.
        /// </summary>
        internal static string ASPxGanttStringId_ResourcesDeleteConfirmation {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.ResourcesDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string ASPxGanttStringId_Start {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot move task &apos;{0}&apos; from task &apos;{1}&apos; because this change would conflict with dependency rules. You can cancel this operation or delete the dependency to proceed..
        /// </summary>
        internal static string ASPxGanttStringId_TaskCriticalLinkedWarning {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.TaskCriticalLinkedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting a task also deletes all its dependencies and subtasks.&lt;br /&gt;Are you sure you want to delete this task?.
        /// </summary>
        internal static string ASPxGanttStringId_TaskDeleteConfirmation {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.TaskDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Details.
        /// </summary>
        internal static string ASPxGanttStringId_TaskDetails {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.TaskDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You try to move the &apos;{0}&apos; task linked by a dependency relation with the &apos;{1}&apos; task. How would you like to proceed?.
        /// </summary>
        internal static string ASPxGanttStringId_TaskLinkedWarning {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.TaskLinkedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string ASPxGanttStringId_Title {
            get {
                return ResourceManager.GetString("ASPxGanttStringId.Title", resourceCulture);
            }
        }
    }
}
