//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxSpellChecker_v20_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxSpellChecker_v20_1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxSpellChecker_v20_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Dictionary.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_AddToDictionaryButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.AddToDictionaryButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_CancelButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change All.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_ChangeAllButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.ChangeAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_ChangeButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.ChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change To:.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_ChangeTo {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.ChangeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose which dictionary to use when checking your spelling..
        /// </summary>
        internal static string ASPxSpellCheckerStringId_ChooseDictionary {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.ChooseDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_CloseButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The spelling check is complete..
        /// </summary>
        internal static string ASPxSpellCheckerStringId_FinishSpellChecking {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.FinishSpellChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General options.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_GeneralOptions {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.GeneralOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore All.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreAllButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore e-mails.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreEmails {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore words in MiXeDcAsE.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreMixedCase {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreMixedCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore words with numbers.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreNumbers {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Once.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreOnceButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreOnceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore markup tags.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreTags {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore words in UPPERCASE.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreUppercase {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore URLs.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_IgnoreUrls {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.IgnoreUrls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International dictionaries.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_InternationalDictionaries {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.InternationalDictionaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_Language {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (No Suggestions).
        /// </summary>
        internal static string ASPxSpellCheckerStringId_NoSuggestionsText {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.NoSuggestionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not in Dictionary:.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_NotInDictionary {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.NotInDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_OkButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options....
        /// </summary>
        internal static string ASPxSpellCheckerStringId_OptionsButton {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.OptionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelling Options.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_OptionsFormCaption {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.OptionsFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Spelling.
        /// </summary>
        internal static string ASPxSpellCheckerStringId_SpellCheckFormCaption {
            get {
                return ResourceManager.GetString("ASPxSpellCheckerStringId.SpellCheckFormCaption", resourceCulture);
            }
        }
    }
}
