//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_v20_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_v20_1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_v20_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading image.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_AltLoadingPanelImage {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_AltLoadingPanelImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted ascending.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_AscendingSortOrder {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_AscendingSortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was changed.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_BatchChanged {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_BatchChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has {0} check box.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_BatchCheckBoxDescriptionFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_BatchCheckBoxDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to row deleted.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_BatchDeletedRow {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_BatchDeletedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} editable cell.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_BatchEditableCellFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_BatchEditableCellFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to row focused.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_BatchFocusedRow {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_BatchFocusedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to row focused and selected.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_BatchFocusedSelectedRow {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_BatchFocusedSelectedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not editable cell.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_BatchNotEditableCellFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_BatchNotEditableCellFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has {0} progress bar.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_BatchProgressBarDescriptionFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_BatchProgressBarDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has {0} radio button.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_BatchRadioButtonDescriptionFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_BatchRadioButtonDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to row selected.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_BatchSelectedRow {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_BatchSelectedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blank.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_BlankEditor {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_BlankEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear value.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ButtonEditClearButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ButtonEditClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipsis.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ButtonEditEllipsisButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ButtonEditEllipsisButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar. Use arrow keys to navigate..
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_CalendarDescription {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_CalendarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can select {0} only..
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_CalendarPickerTypeText {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_CalendarPickerTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decades.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_CalendarPickerTypeTextDecadesPlaceholder {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_CalendarPickerTypeTextDecadesPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_CalendarPickerTypeTextMonthsPlaceholder {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_CalendarPickerTypeTextMonthsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_CalendarPickerTypeTextYearsPlaceholder {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_CalendarPickerTypeTextYearsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card {0} of {1}.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_CardViewCardDescriptionFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_CardViewCardDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection state of card {0}.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_CardViewSelectCardStateCheckBoxFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_CardViewSelectCardStateCheckBoxFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check box column.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_CheckBoxColumnHeader {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_CheckBoxColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2}, {0} of {1}.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_CheckBoxListItemFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_CheckBoxListItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checked.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_Checked {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected dates are: .
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ClientCalendarMultiSelect {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ClientCalendarMultiSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from {0} to {1}.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ClientCalendarRangeFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ClientCalendarRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdown color table is closed..
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ColorEditCollapsedState {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ColorEditCollapsedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color editor..
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ColorEditDescription {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ColorEditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set automatic color.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ColorNestedControlAutomaticColorDescription {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ColorNestedControlAutomaticColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to column {0} of {1}.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ColorNestedControlColumnPositionFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ColorNestedControlColumnPositionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open color picker, button.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ColorNestedControlCustomButtonDescription {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ColorNestedControlCustomButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a color by arrow keys.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ColorNestedControlDescription {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ColorNestedControlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select custom color.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ColorNestedControlEmptyColorCellDescription {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ColorNestedControlEmptyColorCellDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to row {0} of {1}.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ColorNestedControlRowPositionFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ColorNestedControlRowPositionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color {0}.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ColorNestedControlTableValueFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ColorNestedControlTableValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use arrow down key to open color table.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ColorNestedControlToolbarButtonDescription {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ColorNestedControlToolbarButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEX.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ColorPickerHexInputDescription {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ColorPickerHexInputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current text is {2} .
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ComboBoxCurrentTextFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ComboBoxCurrentTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The found item count is {0}. The selected item text is {1}. .
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ComboBoxFilteringResultFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ComboBoxFilteringResultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdown calendar is closed..
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_DateEditCollapsedState {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_DateEditCollapsedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date editor..
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_DateEditDescription {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_DateEditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback in process..
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_DefaultCallback {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_DefaultCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted descending.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_DescendingSortOrder {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_DescendingSortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_DropDownApplyButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_DropDownApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_DropDownCloseButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_DropDownCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open or close the drop-down window.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_DropDownEditDropDownButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_DropDownEditDropDownButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to empty.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_EmptyItem {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_EmptyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a filter condition.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_FilterControlConditionEditor {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_FilterControlConditionEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter for {0} column..
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_FilterEditorFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_FilterEditorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply filter state.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_GridFilterBarCheckBoxDescription {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_GridFilterBarCheckBoxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bar used to filter grid data.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_GridFilterBarDescription {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_GridFilterBarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter applied.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_GridHeaderFilterButtonActive {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_GridHeaderFilterButtonActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open filter options for {0} column. {1}.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_GridHeaderFilterButtonFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_GridHeaderFilterButtonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not filtered.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_GridHeaderFilterButtonInactive {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_GridHeaderFilterButtonInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter options. Use Enter key to immediately apply or Escape to cancel.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_GridHeaderFilterPopupDescription {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_GridHeaderFilterPopupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The grid&apos;s search panel..
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_GridSearchPanelDescription {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_GridSearchPanelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A grid status bar.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_GridStatusBarDescription {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_GridStatusBarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A horizontal toolbar used to execute commands associated with the parent grid..
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_GridToolbarDescription {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_GridToolbarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data table related to the headers above.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_GridViewDataTableCaption {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_GridViewDataTableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter criteria for {0} column.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_GridViewFilterRowButtonFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_GridViewFilterRowButtonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter for {0} column. Displays data records whose column value {1} the filter value..
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_GridViewFilterRowEditorFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_GridViewFilterRowEditorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer table related to the header and data tables above.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_GridViewFooterTableCaption {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_GridViewFooterTableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} header column. .
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_GridViewHeaderLinkFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_GridViewHeaderLinkFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers for the data table below.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_GridViewHeaderTableCaption {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_GridViewHeaderTableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection state of row {0}.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_GridViewSelectRowStateCheckBoxFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_GridViewSelectRowStateCheckBoxFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user content.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_IFrameTitle {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_IFrameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , {0} of {1}.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ItemPositionFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ItemPositionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListBox. Use arrow keys to navigate..
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ListBoxDescription {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ListBoxDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide filter.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ListBoxHideFilter {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ListBoxHideFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show filter.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ListBoxShowFilter {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ListBoxShowFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_Menu {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show hidden items.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_MenuAdaptivityEllipsisItem {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_MenuAdaptivityEllipsisItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menubar.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_MenuBar {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_MenuBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_MenuHorizontal {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_MenuHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to level.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_MenuLevel {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_MenuLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show sub menu.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_MenuShowSubMenu {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_MenuShowSubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_MenuVertical {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_MenuVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation bar. Use the Tab key for navigation..
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_NavBarDescription {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_NavBarDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not sorted.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_NoneSortOrder {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_NoneSortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pager used to navigate through the parent control&apos;s data..
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_PagerDescription {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_PagerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_PagerSummaryFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_PagerSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close popup.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_PopupControlClose {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_PopupControlClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating Control. Current value is {0}.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_RatingControlDescription {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_RatingControlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0} of {1}.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_RatingControlItemLabel {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_RatingControlItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show filter builder dialog.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ShowGridFilterBuilderDialog {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ShowGridFilterBuilderDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrement by {0}.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_SpinEditDecrementButtonFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_SpinEditDecrementButtonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment by {0}.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_SpinEditIncrementButtonFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_SpinEditIncrementButtonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} column {1} value, .
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_TableItemFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_TableItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This input displays selected file names.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_TitleForFakeInput {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_TitleForFakeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use check boxes to select nodes..
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_TreeListCheckBoxSelectionDescription {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_TreeListCheckBoxSelectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_TreeListCollapse {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_TreeListCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} button. Row {1}.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_TreeListCollapseExpandButtonFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_TreeListCollapseExpandButtonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A TreeList with {0} rows and {1} columns. .
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_TreeListDescriptionFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_TreeListDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect all nodes.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_TreeListDeselectAllCheckBox {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_TreeListDeselectAllCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_TreeListExpand {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_TreeListExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header cell. {0} column, {1}. Sort.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_TreeListHeaderLinkFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_TreeListHeaderLinkFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0}..
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_TreeListLevelFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_TreeListLevelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Tab key to navigate. Use the Enter key to expand or collapse nodes. .
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_TreeListNavigationDescription {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_TreeListNavigationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapsed. .
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_TreeListNodeCollapsedState {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_TreeListNodeCollapsedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded. .
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_TreeListNodeExpandedState {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_TreeListNodeExpandedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row not selected..
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_TreeListNotSelectedRow {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_TreeListNotSelectedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all nodes.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_TreeListSelectAllCheckBox {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_TreeListSelectAllCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row selected..
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_TreeListSelectedRow {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_TreeListSelectedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check state.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_TreeViewNodeCheckState {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_TreeViewNodeCheckState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unchecked.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_Unchecked {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_Unchecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and editor is focused.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_ValidationSummaryFocusedEditor {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_ValidationSummaryFocusedEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open filter options for {0} record. {1}.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_VerticalGridHeaderFilterButtonFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_VerticalGridHeaderFilterButtonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} row header. .
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_VerticalGridHeaderLinkFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_VerticalGridHeaderLinkFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection state of record {0}.
        /// </summary>
        internal static string ASPxperienceStringId_Accessibility_VerticalGridSelectRecordStateCheckBoxFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Accessibility_VerticalGridSelectRecordStateCheckBoxFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Callback request failed due to an internal server error..
        /// </summary>
        internal static string ASPxperienceStringId_CallbackGenericErrorText {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.CallbackGenericErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to display.
        /// </summary>
        internal static string ASPxperienceStringId_DataViewBase_EmptyDataText {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.DataViewBase_EmptyDataText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size:.
        /// </summary>
        internal static string ASPxperienceStringId_DataView_PagerPageSize {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.DataView_PagerPageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows per page:.
        /// </summary>
        internal static string ASPxperienceStringId_DataView_PagerRowPerPage {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.DataView_PagerRowPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All pages.
        /// </summary>
        internal static string ASPxperienceStringId_DataView_PagerSummaryAllPages {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.DataView_PagerSummaryAllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        internal static string ASPxperienceStringId_DataView_PagerSummaryFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.DataView_PagerSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more items....
        /// </summary>
        internal static string ASPxperienceStringId_DataView_ShowMoreItemsText {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.DataView_ShowMoreItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is impossible to save to an already opened file..
        /// </summary>
        internal static string ASPxperienceStringId_Documents_CantSaveToAlreadyOpenedFileMessage {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Documents_CantSaveToAlreadyOpenedFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_Cancel {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &apos;{0}&apos;?.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_DeleteConfirm {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access prohibited. The operation cannot be completed.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorAccessProhibited {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorAccessProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file/folder already exists.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorAlreadyExists {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to access a remote cloud service.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorCloudAccessFailed {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorCloudAccessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder not found.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorFolderNotFound {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name contains invalid characters. The operation cannot be completed.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorInvalidSymbols {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorInvalidSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified IO error. The operation cannot be completed.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorIO {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file/folder name cannot be empty.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied. The operation cannot be completed.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorNoAccess {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorNoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified error.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorOther {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified path, file name, or both are too long.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorPathToLong {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorPathToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root folder is not specified or does not exist.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorRootFolderNotSpecified {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorRootFolderNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No access to the thumbnail folder.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorThumbnail {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The upload was unsuccessful for {0} of {1} files.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorUploadSeveralFiles {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorUploadSeveralFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation cannot be completed because the file/folder is being used by another process.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorUsedByAnotherProcess {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorUsedByAnotherProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file extension is not allowed. The operation cannot be completed.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorWrongExtension {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorWrongExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of directories in relativeName must be equal to the idPath array length..
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_ErrorWrongIdPathLength {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_ErrorWrongIdPathLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_FileInfoTypeCaption_FileName {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_FileInfoTypeCaption_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date modified.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_FileInfoTypeCaption_LastWriteTime {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_FileInfoTypeCaption_LastWriteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_FileInfoTypeCaption_Location {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_FileInfoTypeCaption_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_FileInfoTypeCaption_Size {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_FileInfoTypeCaption_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by:.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_Filter {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_Folder {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Destination Folder.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_FolderBrowserPopupHeader {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_FolderBrowserPopupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked for upload.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_FolderLocked {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_FolderLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 days.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_GridViewFilter_DateMonth {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_GridViewFilter_DateMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_GridViewFilter_DateToday {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_GridViewFilter_DateToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 days.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_GridViewFilter_DateWeek {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_GridViewFilter_DateWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 365 days.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_GridViewFilter_DateYear {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_GridViewFilter_DateYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty ({0}).
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_GridViewFilter_SizeEmpty {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_GridViewFilter_SizeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gigantic ({0}).
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_GridViewFilter_SizeGigantic {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_GridViewFilter_SizeGigantic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huge ({0}).
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_GridViewFilter_SizeHuge {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_GridViewFilter_SizeHuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large ({0}).
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_GridViewFilter_SizeLarge {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_GridViewFilter_SizeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium ({0}).
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_GridViewFilter_SizeMedium {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_GridViewFilter_SizeMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small ({0}).
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_GridViewFilter_SizeSmall {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_GridViewFilter_SizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiny ({0}).
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_GridViewFilter_SizeTiny {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_GridViewFilter_SizeTiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_InformationUnitSymbol {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_InformationUnitSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewFolder.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_NewFolderName {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_NewFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_Ok {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_Path {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_SelectAll {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_TbCopy {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_TbCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create (F7).
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_TbCreate {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_TbCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete (Del).
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_TbDelete {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_TbDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_TbDownload {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_TbDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand/collapse folder container.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_TbExpandFolderContainer {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_TbExpandFolderContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move (F6).
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_TbMove {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_TbMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_TbRefresh {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_TbRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename (F2).
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_TbRename {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_TbRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading....
        /// </summary>
        internal static string ASPxperienceStringId_FileManager_UploadProgressPopupText {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.FileManager_UploadProgressPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string ASPxperienceStringId_ImageZoom_HintText {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.ImageZoom_HintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Table.
        /// </summary>
        internal static string ASPxperienceStringId_InsertTableControl_InsertTable {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.InsertTableControl_InsertTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading&amp;hellip;.
        /// </summary>
        internal static string ASPxperienceStringId_Loading {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to top.
        /// </summary>
        internal static string ASPxperienceStringId_NewsControl_BackToTop {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.NewsControl_BackToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page:.
        /// </summary>
        internal static string ASPxperienceStringId_NewsControl_Page {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.NewsControl_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string ASPxperienceStringId_Pager_All {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string ASPxperienceStringId_Pager_First {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string ASPxperienceStringId_Pager_Last {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string ASPxperienceStringId_Pager_Next {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size:.
        /// </summary>
        internal static string ASPxperienceStringId_Pager_PageSize {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string ASPxperienceStringId_Pager_PageSizeAllItem {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_PageSizeAllItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        internal static string ASPxperienceStringId_Pager_Prev {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages: {0} - {1} ({2} items).
        /// </summary>
        internal static string ASPxperienceStringId_Pager_SummaryAllPagesFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_SummaryAllPagesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to paginate.
        /// </summary>
        internal static string ASPxperienceStringId_Pager_SummaryEmptyText {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_SummaryEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1} ({2} items).
        /// </summary>
        internal static string ASPxperienceStringId_Pager_SummaryFormat {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Pager_SummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ASPxperienceStringId_PopupControl_CloseButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.PopupControl_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse/Expand.
        /// </summary>
        internal static string ASPxperienceStringId_PopupControl_CollapseButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.PopupControl_CollapseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize/Restore.
        /// </summary>
        internal static string ASPxperienceStringId_PopupControl_MaximizeButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.PopupControl_MaximizeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin/Unpin.
        /// </summary>
        internal static string ASPxperienceStringId_PopupControl_PinButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.PopupControl_PinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string ASPxperienceStringId_PopupControl_RefreshButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.PopupControl_RefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        internal static string ASPxperienceStringId_PopupControl_SizeGrip {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.PopupControl_SizeGrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string ASPxperienceStringId_Ribbon_FileTabText {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.Ribbon_FileTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse/Expand.
        /// </summary>
        internal static string ASPxperienceStringId_RoundPanel_CollapseButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.RoundPanel_CollapseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This control cannot be rendered in the Design view for the current project type.
        /// </summary>
        internal static string ASPxperienceStringId_SharePoint_DesignTime_EmptyView {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.SharePoint_DesignTime_EmptyView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Back to Top].
        /// </summary>
        internal static string ASPxperienceStringId_TitleIndex_BackToTop {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.TitleIndex_BackToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:&amp;nbsp;&amp;nbsp;&amp;nbsp;.
        /// </summary>
        internal static string ASPxperienceStringId_TitleIndex_FilterCaption {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.TitleIndex_FilterCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;?&lt;/b&gt; = any single character
        ///&lt;b&gt;*&lt;/b&gt; = any characters.
        /// </summary>
        internal static string ASPxperienceStringId_TitleIndex_FilterHint {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.TitleIndex_FilterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data for this filter criteria.
        /// </summary>
        internal static string ASPxperienceStringId_TitleIndex_NoData {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.TitleIndex_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string ASPxperienceStringId_TreeView_AltCollapse {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.TreeView_AltCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        internal static string ASPxperienceStringId_TreeView_AltExpand {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.TreeView_AltExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string ASPxperienceStringId_TreeView_AltLoading {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.TreeView_AltLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the server path &quot;{0}&quot; is denied. The reason might be due to lack of permissions to write files in this (or parent) folder..
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_AccessDeniedError {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_AccessDeniedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_AddButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_BrowseButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_BrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web server returned unexpected response..
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_CallbackResultIncorrectError {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_CallbackResultIncorrectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_CancelButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear selection.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_ClearFileSelectionButtonToolTip {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_ClearFileSelectionButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You dragged more than one file, whereas multiple file selection is not allowed. Please drag a single file only..
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_DragAndDropMoreThanOneFileError {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_DragAndDropMoreThanOneFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop file(s) here.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_DropZone {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_DropZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploading fails because the form&apos;s enctype attribute is not set to &apos;multipart/form-data&apos;.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_EnctypeError {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_EnctypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploading file &apos;{0}&apos; doesn&apos;t exist.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_FileDoesNotExistError {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_FileDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload failed due to an external error.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_GeneralError {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name contains invalid characters..
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_InvalidWindowsFileName {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_InvalidWindowsFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file(s) have been removed from the selection because they exceed the limit of files to be uploaded at once (which is set to {1})..
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_MaxFileCountError {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_MaxFileCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size exceeds the maximum allowed size, which is {0} bytes.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_MaxSize {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_MaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! 
        ///
        ///{0} files are invalid and will not be uploaded. Possible reasons are: they exceed the allowed file size ({1}), their extensions are not allowed, or their filenames contain invalid characters. These files have been removed from the selection: 
        ///
        ///{2}.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_MultiSelection {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_MultiSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This content type isn&apos;t allowed.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_NotAllowedContentTypes {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_NotAllowedContentTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file extension isn&apos;t allowed.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_NotAllowedFileExtension {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_NotAllowedFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file upload cannot be completed due to an operation timeout. Reload the web page and upload your file(s) once again..
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_OperationTimeoutError {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_OperationTimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use a browser with HTML5 support; or install &lt;a href=&quot;{0}&quot;&gt;Microsoft Silverlight v3 or later&lt;/a&gt; to view this content and have an ability to upload files..
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_PlatformErrorText {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_PlatformErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_RemoveButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files are selected for upload.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_SelectedSeveralFiles {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_SelectedSeveralFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired. Please refresh the page to continue..
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_SessionHasExpiredError {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_SessionHasExpiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many files are selected. Reduce the number of selected files and try again..
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_TooManyFilesError {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_TooManyFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server encountered an internal unspecified error that prevented it from fulfilling the request..
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_UnspecifiedError {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_UnspecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_UploadButton {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_UploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your browser does not support this file upload mode..
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_UploadModeNotSupported {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_UploadModeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload was canceled..
        /// </summary>
        internal static string ASPxperienceStringId_UploadControl_UploadWasCanceledError {
            get {
                return ResourceManager.GetString("ASPxperienceStringId.UploadControl_UploadWasCanceledError", resourceCulture);
            }
        }
    }
}
