//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxScheduler_v20_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxScheduler_v20_1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxScheduler_v20_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No appointments to display.
        /// </summary>
        internal static string ASPxSchedulerStringId_Agenda_NoAppointmentsToDisplay {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Agenda_NoAppointmentsToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string ASPxSchedulerStringId_CaptionViewNavigator_Today {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.CaptionViewNavigator_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Day {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day(s).
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Days {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_DeleteRecurrentApt {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_DeleteRecurrentApt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show detail info.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_DetailInfo {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_DetailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_EndDate {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Error {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Every {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every weekday.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_EveryWeekday {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_EveryWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Date.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_GotoDate {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_GotoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Hour {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Info {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t load {0}.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_LoadError {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month(s).
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Months {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to occurrences.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Occurrences {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Occurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Of {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of  every.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_OfEvery {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_OfEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Recurring Item.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_OpenRecurrentApt {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_OpenRecurrentApt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press ESC to cancel operation.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_OperationToolTip {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_OperationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recur every.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurEvery {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrence.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Recurrence {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Recurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End by:.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurrenceRange_EndBy {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurrenceRange_EndBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No end date.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurrenceRange_NoEndDate {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurrenceRange_NoEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End after:.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurrenceRange_OccurrenceCount {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurrenceRange_OccurrenceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurrenceType_Daily {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurrenceType_Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurrenceType_Hourly {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurrenceType_Hourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurrenceType_Monthly {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurrenceType_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurrenceType_Weekly {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurrenceType_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yearly.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_RecurrenceType_Yearly {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_RecurrenceType_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_ShowMore {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_The {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_The", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:D} &amp;ndash; {1:D}.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_ViewVisibleInterval_Format {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_ViewVisibleInterval_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_Warning {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week(s) on:.
        /// </summary>
        internal static string ASPxSchedulerStringId_Caption_WeeksOn {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Caption_WeeksOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ASPxSchedulerStringId_FloatingActionButton_DeleteAppointment {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.FloatingActionButton_DeleteAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ASPxSchedulerStringId_FloatingActionButton_EditAppointment {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.FloatingActionButton_EditAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Appointment.
        /// </summary>
        internal static string ASPxSchedulerStringId_FloatingActionButton_NewAppointment {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.FloatingActionButton_NewAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Recurring Appointment.
        /// </summary>
        internal static string ASPxSchedulerStringId_FloatingActionButton_NewRecurringAppointment {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.FloatingActionButton_NewRecurringAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All day event.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_AllDayEvent {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_AllDayEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_ButtonCancel {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_ButtonDelete {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_ButtonDismiss {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_ButtonDismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss All.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_ButtonDismissAll {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_ButtonDismissAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_ButtonOk {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Item.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_ButtonOpenItem {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_ButtonOpenItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snooze.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_ButtonSnooze {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_ButtonSnooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete all occurrences of the recurring appointment &quot;{0}&quot;, or just this one?.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_ConfirmDelete {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is a recurring appointment. Do you want to open only this occurrence or the series?.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_ConfirmEdit {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_ConfirmEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_Date {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time:.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_EndTime {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label:.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_Label {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_Location {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This occurrence.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_Occurrence {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_Occurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Edit Form....
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_OpenEditForm {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_OpenEditForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrence.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_Recurrence {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_Recurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_Reminder {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource:.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_Resource {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_Save {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The series.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_Series {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in:.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_ShowIn {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_ShowIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Snooze to be reminded again in:.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_SnoozeInfo {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_SnoozeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time:.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_StartTime {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show time as:.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_Status {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject:.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_Subject {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone:.
        /// </summary>
        internal static string ASPxSchedulerStringId_Form_TimeZone {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Form_TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource name....
        /// </summary>
        internal static string ASPxSchedulerStringId_Resources_FilterNullText {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Resources_FilterNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show resources filter window.
        /// </summary>
        internal static string ASPxSchedulerStringId_Resources_ShowFilterWindow {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.Resources_ShowFilterWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward.
        /// </summary>
        internal static string ASPxSchedulerStringId_TooltipViewNavigator_Backward {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.TooltipViewNavigator_Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string ASPxSchedulerStringId_TooltipViewNavigator_Forward {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.TooltipViewNavigator_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Date.
        /// </summary>
        internal static string ASPxSchedulerStringId_TooltipViewNavigator_GotoDate {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.TooltipViewNavigator_GotoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ASPxSchedulerStringId_ToolTip_DeleteAppointment {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.ToolTip_DeleteAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ASPxSchedulerStringId_ToolTip_EditAppointment {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.ToolTip_EditAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string ASPxSchedulerStringId_ToolTip_Loading {
            get {
                return ResourceManager.GetString("ASPxSchedulerStringId.ToolTip_Loading", resourceCulture);
            }
        }
    }
}
