//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxDiagram_v20_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxDiagram_v20_1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxDiagram_v20_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto zoom by content.
        /// </summary>
        internal static string ASPxDiagramStringId_AutoZoomByContent {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.AutoZoomByContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto zoom by width.
        /// </summary>
        internal static string ASPxDiagramStringId_AutoZoomByWidth {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.AutoZoomByWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring To Front.
        /// </summary>
        internal static string ASPxDiagramStringId_BringToFront {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.BringToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Shape Image....
        /// </summary>
        internal static string ASPxDiagramStringId_ChangeShapeImage {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.ChangeShapeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string ASPxDiagramStringId_ConnectorEnd {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.ConnectorEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow.
        /// </summary>
        internal static string ASPxDiagramStringId_ConnectorLineEndingArrow {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.ConnectorLineEndingArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string ASPxDiagramStringId_ConnectorLineEndingNone {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.ConnectorLineEndingNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string ASPxDiagramStringId_ConnectorStart {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.ConnectorStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ASPxDiagramStringId_ConnectorType {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.ConnectorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orthogonal.
        /// </summary>
        internal static string ASPxDiagramStringId_ConnectorTypeOrthogonal {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.ConnectorTypeOrthogonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight.
        /// </summary>
        internal static string ASPxDiagramStringId_ConnectorTypeStraight {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.ConnectorTypeStraight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string ASPxDiagramStringId_Copy {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string ASPxDiagramStringId_Cut {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ASPxDiagramStringId_Delete {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Shape Image.
        /// </summary>
        internal static string ASPxDiagramStringId_DeleteShapeImage {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.DeleteShapeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ASPxDiagramStringId_Dialog_Button_Cancel {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Dialog_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ASPxDiagramStringId_Dialog_Button_OK {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Dialog_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Image.
        /// </summary>
        internal static string ASPxDiagramStringId_Dialog_ShapeImage_Change_Header {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Dialog_ShapeImage_Change_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Image.
        /// </summary>
        internal static string ASPxDiagramStringId_Dialog_ShapeImage_Insert_Header {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Dialog_ShapeImage_Insert_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse your computer for the image file to upload.
        /// </summary>
        internal static string ASPxDiagramStringId_Dialog_ShapeImage_Upload_Caption {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Dialog_ShapeImage_Upload_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ASPxDiagramStringId_Export {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill color.
        /// </summary>
        internal static string ASPxDiagramStringId_FillColor {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.FillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to content.
        /// </summary>
        internal static string ASPxDiagramStringId_FitToContent {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.FitToContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to width.
        /// </summary>
        internal static string ASPxDiagramStringId_FitToWidth {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.FitToWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen.
        /// </summary>
        internal static string ASPxDiagramStringId_Fullscreen {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Shape Image....
        /// </summary>
        internal static string ASPxDiagramStringId_InsertShapeImage {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.InsertShapeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom-to-top.
        /// </summary>
        internal static string ASPxDiagramStringId_LayoutBottomToTop {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.LayoutBottomToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left-to-right.
        /// </summary>
        internal static string ASPxDiagramStringId_LayoutLeftToRight {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.LayoutLeftToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-to-left.
        /// </summary>
        internal static string ASPxDiagramStringId_LayoutRightToLeft {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.LayoutRightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top-to-bottom.
        /// </summary>
        internal static string ASPxDiagramStringId_LayoutTopToBottom {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.LayoutTopToBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line color.
        /// </summary>
        internal static string ASPxDiagramStringId_LineColor {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.LineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line style.
        /// </summary>
        internal static string ASPxDiagramStringId_LineStyle {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.LineStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashed.
        /// </summary>
        internal static string ASPxDiagramStringId_LineStyleDashed {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.LineStyleDashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dotted.
        /// </summary>
        internal static string ASPxDiagramStringId_LineStyleDotted {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.LineStyleDotted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid.
        /// </summary>
        internal static string ASPxDiagramStringId_LineStyleSolid {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.LineStyleSolid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line width.
        /// </summary>
        internal static string ASPxDiagramStringId_LineWidth {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.LineWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        internal static string ASPxDiagramStringId_Lock {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page color.
        /// </summary>
        internal static string ASPxDiagramStringId_PageColor {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.PageColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        internal static string ASPxDiagramStringId_PageOrientation {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.PageOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        internal static string ASPxDiagramStringId_PageOrientationLandscape {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.PageOrientationLandscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        internal static string ASPxDiagramStringId_PageOrientationPortrait {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.PageOrientationPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string ASPxDiagramStringId_PageSize {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string ASPxDiagramStringId_Paste {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram.
        /// </summary>
        internal static string ASPxDiagramStringId_Properties_Diagram {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Properties_Diagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string ASPxDiagramStringId_Properties_Diagram_Page {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Properties_Diagram_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string ASPxDiagramStringId_Properties_Layout {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Properties_Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layered.
        /// </summary>
        internal static string ASPxDiagramStringId_Properties_Layout_Layered {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Properties_Layout_Layered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree.
        /// </summary>
        internal static string ASPxDiagramStringId_Properties_Layout_Tree {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Properties_Layout_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string ASPxDiagramStringId_Properties_Style {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Properties_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector.
        /// </summary>
        internal static string ASPxDiagramStringId_Properties_Style_Connector {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Properties_Style_Connector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string ASPxDiagramStringId_Properties_Style_Object {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Properties_Style_Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string ASPxDiagramStringId_Properties_Style_Text {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Properties_Style_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string ASPxDiagramStringId_Redo {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string ASPxDiagramStringId_SelectAll {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send To Back.
        /// </summary>
        internal static string ASPxDiagramStringId_SendToBack {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.SendToBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string ASPxDiagramStringId_Settings {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down Arrow.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_ArrowDown {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_ArrowDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Arrow.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_ArrowLeft {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_ArrowLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Right Arrow.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_ArrowLeftRight {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_ArrowLeftRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Arrow.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_ArrowRight {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_ArrowRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up Arrow.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_ArrowUp {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_ArrowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up Down Arrow.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_ArrowUpDown {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_ArrowUpDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person&apos;s Name.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_CardDefaultText {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_CardDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card with Image on the Left.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_CardWithImageOnLeft {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_CardWithImageOnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card with Image on the Right.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_CardWithImageOnRight {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_CardWithImageOnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card with Image on the Top.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_CardWithImageOnTop {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_CardWithImageOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connector.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Connector {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Connector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_ContainerDefaultText {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_ContainerDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Cross {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Cross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Data {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Database {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Decision {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Delay {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Diamond {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Diamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Display {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Document {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ellipse.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Ellipse {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Ellipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard Disk.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_HardDisk {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_HardDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Heart {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Heart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexagon.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Hexagon {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Hexagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal Container.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_HorizontalContainer {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_HorizontalContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Storage.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_InternalStorage {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_InternalStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Input.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_ManualInput {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_ManualInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Operation.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_ManualOperation {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_ManualOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Merge {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Documents.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_MultipleDocuments {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_MultipleDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octagon.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Octagon {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Octagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Or {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper Tape.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_PaperTape {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_PaperTape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pentagon.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Pentagon {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Pentagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefined Process.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_PredefinedProcess {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_PredefinedProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparation.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Preparation {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Preparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Process {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Rectangle {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Star {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Data.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_StoredData {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_StoredData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summing Junction.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_SummingJunction {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_SummingJunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminator.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Terminator {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Terminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Text {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_Triangle {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_Triangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Container.
        /// </summary>
        internal static string ASPxDiagramStringId_Shape_VerticalContainer {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Shape_VerticalContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Grid.
        /// </summary>
        internal static string ASPxDiagramStringId_ShowGrid {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.ShowGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Toolbox.
        /// </summary>
        internal static string ASPxDiagramStringId_ShowToolbox {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.ShowToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple view.
        /// </summary>
        internal static string ASPxDiagramStringId_SimpleView {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.SimpleView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap to Grid.
        /// </summary>
        internal static string ASPxDiagramStringId_SnapToGrid {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.SnapToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align center.
        /// </summary>
        internal static string ASPxDiagramStringId_TextAlignCenter {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.TextAlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align left.
        /// </summary>
        internal static string ASPxDiagramStringId_TextAlignLeft {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.TextAlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align right.
        /// </summary>
        internal static string ASPxDiagramStringId_TextAlignRight {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.TextAlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string ASPxDiagramStringId_TextBold {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.TextBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font color.
        /// </summary>
        internal static string ASPxDiagramStringId_TextFontColor {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.TextFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string ASPxDiagramStringId_TextItalic {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.TextItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        internal static string ASPxDiagramStringId_TextUnderline {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.TextUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ASPxDiagramStringId_ToolboxSearchNullText {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.ToolboxSearchNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Containers.
        /// </summary>
        internal static string ASPxDiagramStringId_Toolbox_Containers {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Toolbox_Containers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string ASPxDiagramStringId_Toolbox_Custom {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Toolbox_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flowchart.
        /// </summary>
        internal static string ASPxDiagramStringId_Toolbox_Flowchart {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Toolbox_Flowchart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string ASPxDiagramStringId_Toolbox_General {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Toolbox_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Org Chart.
        /// </summary>
        internal static string ASPxDiagramStringId_Toolbox_OrgChart {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Toolbox_OrgChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string ASPxDiagramStringId_Undo {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        internal static string ASPxDiagramStringId_UnitCm {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.UnitCm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string ASPxDiagramStringId_UnitIn {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.UnitIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to px.
        /// </summary>
        internal static string ASPxDiagramStringId_UnitPx {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.UnitPx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        internal static string ASPxDiagramStringId_Unlock {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.Unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string ASPxDiagramStringId_ViewUnits {
            get {
                return ResourceManager.GetString("ASPxDiagramStringId.ViewUnits", resourceCulture);
            }
        }
    }
}
