//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevExpress_Web_ASPxGridView_v20_1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevExpress_Web_ASPxGridView_v20_1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevExpress_Web_ASPxGridView_v20_1", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_Collapse {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down Arrow.
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_DragAndDropArrowDown {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_DragAndDropArrowDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Arrow.
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_DragAndDropArrowLeft {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_DragAndDropArrowLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Arrow.
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_DragAndDropArrowRight {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_DragAndDropArrowRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up Arrow.
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_DragAndDropArrowUp {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_DragAndDropArrowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_DragAndDropHideColumnIcon {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_DragAndDropHideColumnIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_Expand {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open filter row popup menu.
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_FilterRowButton {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_FilterRowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not filtered.
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_HeaderFilterButton {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_HeaderFilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter applied.
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_HeaderFilterButtonActive {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_HeaderFilterButtonActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_SortedAscending {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_SortedAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string ASPxGridViewStringId_Alt_SortedDescending {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Alt_SortedDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begins with.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterBeginsWith {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterBeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterContains {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t contain.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterDoesNotContain {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterEndsWith {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterEquals {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater than.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterGreater {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater than or equal to.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterGreaterOrEqual {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterGreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less than.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterLess {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is less than or equal to.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterLessOrEqual {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterLessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like (&apos;%&apos;, &apos;_&apos;).
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterLike {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two wildcard symbols are supported:
        /// &apos;%&apos; substitutes zero or more characters;
        /// &apos;_&apos; substitutes a single character..
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterLikeToolTip {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterLikeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doesn&apos;t equal.
        /// </summary>
        internal static string ASPxGridViewStringId_AutoFilterNotEqual {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.AutoFilterNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted values.
        /// </summary>
        internal static string ASPxGridViewStringId_BatchEdit_ChangesPreviewDeletedValues {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.BatchEdit_ChangesPreviewDeletedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted values.
        /// </summary>
        internal static string ASPxGridViewStringId_BatchEdit_ChangesPreviewInsertedValues {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.BatchEdit_ChangesPreviewInsertedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated values.
        /// </summary>
        internal static string ASPxGridViewStringId_BatchEdit_ChangesPreviewUpdatedValues {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.BatchEdit_ChangesPreviewUpdatedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customization.
        /// </summary>
        internal static string ASPxGridViewStringId_CardView_CustomizationWindowCaption {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CardView_CustomizationWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more cards....
        /// </summary>
        internal static string ASPxGridViewStringId_CardView_EndlessPagingShowMoreCardsButton {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CardView_EndlessPagingShowMoreCardsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Continued).
        /// </summary>
        internal static string ASPxGridViewStringId_CardView_GroupRow_Continued {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CardView_GroupRow_Continued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by:.
        /// </summary>
        internal static string ASPxGridViewStringId_CardView_GroupSelector_Caption {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CardView_GroupSelector_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string ASPxGridViewStringId_CardView_GroupSelector_ClearGroupingItem {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CardView_GroupSelector_ClearGroupingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows per page:.
        /// </summary>
        internal static string ASPxGridViewStringId_CardView_PagerRowPerPage {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CardView_PagerRowPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Footer.
        /// </summary>
        internal static string ASPxGridViewStringId_CardView_Toolbar_ShowCardFooter {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CardView_Toolbar_ShowCardFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Header.
        /// </summary>
        internal static string ASPxGridViewStringId_CardView_Toolbar_ShowCardHeader {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CardView_Toolbar_ShowCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Panel.
        /// </summary>
        internal static string ASPxGridViewStringId_CardView_Toolbar_ShowHeaderPanel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CardView_Toolbar_ShowHeaderPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandApplyFilter {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandApplySearchPanelFilter {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandApplySearchPanelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel changes.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandBatchEditCancel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandBatchEditCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide preview.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandBatchEditHidePreview {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandBatchEditHidePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview changes.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandBatchEditPreviewChanges {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandBatchEditPreviewChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandBatchEditUpdate {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandBatchEditUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update summaries.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandBatchEditUpdateSummaries {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandBatchEditUpdateSummaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandCancel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandClearFilter {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandClearSearchPanelFilter {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandClearSearchPanelFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandCustomizationDialogApply {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandCustomizationDialogApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandCustomizationDialogClose {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandCustomizationDialogClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandDelete {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect all rows on all pages.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandDeselectAllOnAllPages {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandDeselectAllOnAllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect all rows on this page.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandDeselectAllOnPage {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandDeselectAllOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandEdit {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandHideAdaptiveDetail {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandHideAdaptiveDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandNew {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandRecover {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandRecover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandSelect {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all rows on all pages.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandSelectAllOnAllPages {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandSelectAllOnAllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all rows on this page.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandSelectAllOnPage {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandSelectAllOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string ASPxGridViewStringId_CommandShowAdaptiveDetail {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandShowAdaptiveDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string ASPxGridViewStringId_CommandUpdate {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CommandUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete?.
        /// </summary>
        internal static string ASPxGridViewStringId_ConfirmDelete {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to perform the action? All unsaved grid data will be lost..
        /// </summary>
        internal static string ASPxGridViewStringId_ConfirmOnLosingBatchChanges {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ConfirmOnLosingBatchChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ClearFilter {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Grouping.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ClearGrouping {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ClearGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Sorting.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ClearSorting {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ClearSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse Detail.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_CollapseDetailRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_CollapseDetailRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_CollapseRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_CollapseRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_DeleteRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_EditRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_EditRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand Detail.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ExpandDetailRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ExpandDetailRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ExpandRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ExpandRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_Export {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to {0}.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ExportTo {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ExportTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_FullCollapse {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_FullCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_FullExpand {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_FullExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By This Column.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_GroupByColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_GroupByColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Summary.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_GroupSummaryMenu {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_GroupSummaryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Column.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_HideColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_HideColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_NewRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_NewRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_Refresh {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Column.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ShowColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ShowColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Customization Dialog.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ShowCustomizationDialog {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ShowCustomizationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Chooser.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ShowCustomizationWindow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ShowCustomizationWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Builder....
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ShowFilterEditor {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ShowFilterEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Row.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ShowFilterRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ShowFilterRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Row Menu.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ShowFilterRowMenu {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ShowFilterRowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ShowFooter {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ShowFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Panel.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ShowGroupPanel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ShowGroupPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Panel.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_ShowSearchPanel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_ShowSearchPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Ascending.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_SortAscending {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Descending.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_SortDescending {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_SummaryAverage {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_SummaryAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_SummaryCount {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_SummaryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_SummaryMax {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_SummaryMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_SummaryMin {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_SummaryMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_SummaryNone {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_SummaryNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_SummarySum {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_SummarySum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup.
        /// </summary>
        internal static string ASPxGridViewStringId_ContextMenu_UngroupColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.ContextMenu_UngroupColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Chooser.
        /// </summary>
        internal static string ASPxGridViewStringId_CustomizationDialog_ColumnChooserTab {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CustomizationDialog_ColumnChooserTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Values to Select.
        /// </summary>
        internal static string ASPxGridViewStringId_CustomizationDialog_FilterPageUniqueFilterLoadValues {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CustomizationDialog_FilterPageUniqueFilterLoadValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtering.
        /// </summary>
        internal static string ASPxGridViewStringId_CustomizationDialog_FilterTab {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CustomizationDialog_FilterTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No grouping applied.
        /// </summary>
        internal static string ASPxGridViewStringId_CustomizationDialog_GroupPageEmptyDragArea {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CustomizationDialog_GroupPageEmptyDragArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns to Group.
        /// </summary>
        internal static string ASPxGridViewStringId_CustomizationDialog_GroupPageListArea {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CustomizationDialog_GroupPageListArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        internal static string ASPxGridViewStringId_CustomizationDialog_GroupTab {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CustomizationDialog_GroupTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sorting applied.
        /// </summary>
        internal static string ASPxGridViewStringId_CustomizationDialog_SortPageEmptyDragArea {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CustomizationDialog_SortPageEmptyDragArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns to Sort.
        /// </summary>
        internal static string ASPxGridViewStringId_CustomizationDialog_SortPageListArea {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CustomizationDialog_SortPageListArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        internal static string ASPxGridViewStringId_CustomizationDialog_SortTab {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CustomizationDialog_SortTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Chooser.
        /// </summary>
        internal static string ASPxGridViewStringId_CustomizationWindowCaption {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.CustomizationWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to display.
        /// </summary>
        internal static string ASPxGridViewStringId_EmptyDataRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.EmptyDataRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a column here....
        /// </summary>
        internal static string ASPxGridViewStringId_EmptyHeaders {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.EmptyHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Continued on the next page).
        /// </summary>
        internal static string ASPxGridViewStringId_GroupContinuedOnNextPage {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.GroupContinuedOnNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a column header here to group by that column.
        /// </summary>
        internal static string ASPxGridViewStringId_GroupPanel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.GroupPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterCancelButton {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterFrom {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterLastMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Week.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterLastWeek {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Year.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterLastYear {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterLastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Month.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterNextMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterNextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Week.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterNextWeek {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterNextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Year.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterNextYear {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterNextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterOkButton {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Select All).
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterSelectAll {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (All).
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterShowAllItem {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterShowAllItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Blanks).
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterShowBlanksItem {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterShowBlanksItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Non blanks).
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterShowNonBlanksItem {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterShowNonBlanksItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterThisMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Week.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterThisWeek {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Year.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterThisYear {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterTo {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterToday {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterTomorrow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string ASPxGridViewStringId_HeaderFilterYesterday {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.HeaderFilterYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beyond Next Month.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_BeyondNextMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_BeyondNextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earlier this Month.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_EarlierThisMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_EarlierThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_LastMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Week.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_LastWeek {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later this Month.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_LaterThisMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_LaterThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Month.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_NextMonth {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Week.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_NextWeek {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_NextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_Older {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_Older", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three Weeks Ago.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_ThreeWeeksAgo {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_ThreeWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three Weeks Away.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_ThreeWeeksAway {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_ThreeWeeksAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_Today {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_Tomorrow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Weeks Ago.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_TwoWeeksAgo {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_TwoWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Weeks Away.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_TwoWeeksAway {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_TwoWeeksAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string ASPxGridViewStringId_Outlook_Yesterday {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Outlook_Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Form.
        /// </summary>
        internal static string ASPxGridViewStringId_PopupEditFormCaption {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.PopupEditFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to search....
        /// </summary>
        internal static string ASPxGridViewStringId_SearchPanelEditorNullText {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.SearchPanelEditorNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection state of all rows on all pages.
        /// </summary>
        internal static string ASPxGridViewStringId_SelectAllCheckBoxInAllPagesMode {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.SelectAllCheckBoxInAllPagesMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection state of all rows on this page.
        /// </summary>
        internal static string ASPxGridViewStringId_SelectAllCheckBoxInPageMode {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.SelectAllCheckBoxInPageMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg={0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Average {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg of {1} is {0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Average_OtherColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Average_OtherColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count={0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Count {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max={0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Max {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max of {1} is {0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Max_OtherColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Max_OtherColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min={0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Min {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min of {1} is {0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Min_OtherColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Min_OtherColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum={0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Sum {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of {1} is {0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Summary_Sum_OtherColumn {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Summary_Sum_OtherColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_Cancel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ClearFilter {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Grouping.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ClearGrouping {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ClearGrouping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Sorting.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ClearSorting {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ClearSorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse Detail.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_CollapseDetailRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_CollapseDetailRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_CollapseRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_CollapseRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_Delete {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_Edit {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand Detail.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ExpandDetailRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ExpandDetailRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ExpandRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ExpandRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to {0}.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ExportTo {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ExportTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_FullCollapse {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_FullCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_FullExpand {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_FullExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_New {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_Refresh {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Customization Dialog.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ShowCustomizationDialog {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ShowCustomizationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Chooser.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ShowCustomizationWindow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ShowCustomizationWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Builder....
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ShowFilterEditor {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ShowFilterEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Row.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ShowFilterRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ShowFilterRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Row Menu.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ShowFilterRowMenu {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ShowFilterRowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ShowFooter {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ShowFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Panel.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ShowGroupPanel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ShowGroupPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Panel.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ShowSearchPanel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ShowSearchPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Panel.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_ShowSummaryPanel {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_ShowSummaryPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string ASPxGridViewStringId_Toolbar_Update {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.Toolbar_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse category.
        /// </summary>
        internal static string ASPxGridViewStringId_VerticalGrid_AltCollapseCategory {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.VerticalGrid_AltCollapseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse row.
        /// </summary>
        internal static string ASPxGridViewStringId_VerticalGrid_AltCollapseRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.VerticalGrid_AltCollapseRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand category.
        /// </summary>
        internal static string ASPxGridViewStringId_VerticalGrid_AltExpandCategory {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.VerticalGrid_AltExpandCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand row.
        /// </summary>
        internal static string ASPxGridViewStringId_VerticalGrid_AltExpandRow {
            get {
                return ResourceManager.GetString("ASPxGridViewStringId.VerticalGrid_AltExpandRow", resourceCulture);
            }
        }
    }
}
