//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DocType
    {
        public DocType()
        {
            this.Documents = new HashSet<Document>();
        }
        [Key]
        public int DocTypeID { get; set; }
        public string DocTypeCode { get; set; }
        public string DocTypeName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateStaffID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyStaffID { get; set; }

    
        public virtual ICollection<Document> Documents { get; set; }
    }
}
