//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Document: Auditable
    {
        public Document()
        {
            this.DocIssues = new HashSet<DocIssue>();
        }
        [Key]
        public int DocID { get; set; }
        public string DocCode { get; set; }
        public Nullable<int> DocTypeID { get; set; }
        public string Title { get; set; }
        public string Abstract { get; set; }
    
        public virtual ICollection<DocIssue> DocIssues { get; set; }
        public virtual DocType DocTypes { get; set; }
    }
}
