//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Request: Auditable
    {
        public Request()
        {
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string RegisteredNo { get; set; }
        public string ReceivedNo { get; set; }
        public string ContractNo { get; set; }
        public string CompanyId { get; set; }
        public string EquTypeId { get; set; }
        public string EquGroupId { get; set; }
        public string EquName { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Serial_Imei { get; set; }
        public string MadeIn { get; set; }
        public string Standards { get; set; }
        public string Accessories { get; set; }
        public string SealInfo { get; set; }
        public int HoldEquipNo { get; set; }
        public string Note { get; set; }
        public string RegistedBy { get; set; }
        public string ReceivedBy { get; set; }
        public string AssignedBy { get; set; }
        public string TestedBy { get; set; }
        public string VerifiedyBy { get; set; }
        public string ApprovedBy { get; set; }
        public string ReturnedBy { get; set; }
        public string StatusId { get; set; }

        public Nullable<System.DateTime> RegistedDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
        public Nullable<System.DateTime> TestedDate { get; set; }
        public Nullable<System.DateTime> SentToLinkLabDate { get; set; }
        public Nullable<System.DateTime> ReceivedFromLinkLabDate { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> SealedDate { get; set; }
        public int TestReportId { get; set; }
        public string FeeId { get; set; }
        public long Price { get; set; }
        public Nullable<System.DateTime> ReturnedDate { get; set; }

        [ForeignKey("CompanyId")]
        public virtual Company Company { get; set; }

        [ForeignKey("EquTypeId")]
        public virtual EquType EquType { get; set; }

        [ForeignKey("EquGroupId")]
        public virtual EquGroup EquGroup { get; set; }

        [ForeignKey("StatusId")]
        public virtual Status ReqStatus { get; set; }
        //public virtual TestReport TestReport { get; set; }
        //public virtual Fee Fee { get; set; }
        public virtual ICollection<Opinion> Opinions { get; set; }
    }
}
