//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Role
    {
        public Role()
        {
            this.Authorizes = new HashSet<Authorize>();
        }
        [Key]
        public int RoleID { get; set; }
        public string Role1 { get; set; }
    
        public virtual ICollection<Authorize> Authorizes { get; set; }
    }
}
