//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Skill
    {
        [Key]
        public string StaffID { get; set; }
        public string EquTypeID { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<bool> InActived { get; set; }
        public Nullable<int> Level { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
