//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Staff
    {
        public Staff()
        {
            this.Authorizes = new HashSet<Authorize>();
            this.Handovers = new HashSet<Handover>();
            this.Handovers1 = new HashSet<Handover>();
            this.OrderSts = new HashSet<OrderStatus>();
            this.Skills = new HashSet<Skill>();
        }
        [Key]
        public string StaffID { get; set; }
        public string StaffNo { get; set; }
        public string StaffFistName { get; set; }
        public string StaffLastName { get; set; }
        public string StaffFullName { get; set; }
        public string ID { get; set; }
        public string PhoneNo { get; set; }
        public string HomeAddress { get; set; }
        public string HomePhone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Department { get; set; }
        public string Position { get; set; }
        public string WorkHistory { get; set; }
        public string TrainHistory { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public byte[] StaffImg { get; set; }
        public Nullable<int> InWorking { get; set; }
        public Nullable<int> Enable { get; set; }
    
        public virtual AccessRight AccessRight { get; set; }
        public virtual ICollection<Authorize> Authorizes { get; set; }
        public virtual ICollection<Handover> Handovers { get; set; }
        public virtual ICollection<Handover> Handovers1 { get; set; }
        public virtual ICollection<OrderStatus> OrderSts { get; set; }
        public virtual ICollection<Skill> Skills { get; set; }
    }
}
