//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Standard:Auditable
    {
        [Key]
        public string Id { get; set; }
        public string Name { get; set; }
        public string StdTypeId { get; set; }
        public string Abstract { get; set; }
        public string FileName { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public string FeeDoc { get; set; }
        public int FeePrice { get; set; }
        public string LabID { get; set; }

        [ForeignKey("StdTypeId")]
        public virtual StdType StdType { get; set; }
    }
}
