//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Stationery
    {
        public Stationery()
        {
            this.OrderSts = new HashSet<OrderStatus>();
        }
        [Key]
        public int StID { get; set; }
        public string StName { get; set; }
        public Nullable<float> Price { get; set; }
        public string Note { get; set; }
        public string Unit { get; set; }
    
        public virtual ICollection<OrderStatus> OrderSts { get; set; }
    }
}
