//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TestReport
    {
        [Key]
        public int AssignmentID { get; set; }
        public string RequestID { get; set; }
        public string TestReportNo { get; set; }
        public Nullable<System.DateTime> TestReportIssueDate { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public Nullable<int> TestDateSession { get; set; }
        public string Temperature { get; set; }
        public string Humidity { get; set; }
        public string TestHistory { get; set; }
        public string TestReportNoFull { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> ReturnRPDate { get; set; }
        public string ReturnStaffID { get; set; }
        public Nullable<int> RedBillID { get; set; }
        public Nullable<System.DateTime> ReturnRBDate { get; set; }
        public Nullable<int> HoldTest { get; set; }
        public Nullable<int> HoldRedBill { get; set; }
        public string ReturnRBStaffID { get; set; }
        public Nullable<int> Kind { get; set; }
        public string CreateRPStaff { get; set; }
        public string ApproveStaff { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string TestRPFileName { get; set; }
        public string TestRPURL { get; set; }
    }
}
