//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataVMs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calibration
    {
        public int CalibID { get; set; }
        public Nullable<int> TestSysID { get; set; }
        public string CalibNo { get; set; }
        public string CalibFrom { get; set; }
        public Nullable<System.DateTime> CalibDate { get; set; }
        public Nullable<System.DateTime> EndValidDate { get; set; }
        public string Note { get; set; }
    
        public virtual TestSystem TestSystem { get; set; }
    }
}
