//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataVMs
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocCategoryVM: AuditableVM
    {
        public DocCategoryVM()
        {
            this.DocIns = new HashSet<DocInVM>();
            this.DocOuts = new HashSet<DocOutVM>();
        }
    
        public int DocCatID { get; set; }
        public string DocCatCode { get; set; }
        public string DocCatName { get; set; }
            
        public virtual ICollection<DocInVM> DocIns { get; set; }
        public virtual ICollection<DocOutVM> DocOuts { get; set; }
    }
}
