//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataVMs
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocIssueVM: AuditableVM
    {
        public int IssueID { get; set; }
        public int DocID { get; set; }
        public int IssueNo { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string DecisionNo { get; set; }
        public Nullable<System.DateTime> DecisionDate { get; set; }
        public string NotesOfUpdating { get; set; }
        public string FileName { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
    
        public virtual DocumentVM Documents { get; set; }
    }
}
