//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataVMs
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocTypeVM: AuditableVM
    {
        public DocTypeVM()
        {
            this.Documents = new HashSet<DocumentVM>();
        }
    
        public int DocTypeID { get; set; }
        public string DocTypeCode { get; set; }
        public string DocTypeName { get; set; }
            
        public virtual ICollection<DocumentVM> Documents { get; set; }
    }
}
