//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataVMs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Environment
    {
        public int ID { get; set; }
        public System.DateTime date { get; set; }
        public string tMor { get; set; }
        public string hMor { get; set; }
        public string tAft { get; set; }
        public string hAft { get; set; }
        public string StaffMor { get; set; }
        public string StaffAft { get; set; }
    }
}
