//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataVMs
{
    using Data.DataModels;
    using Data.Extensions;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EquGroupVM: AuditableVM
    {
        [MaxLength(16, ErrorMessage = "Mã nhóm sản phẩm không quá 16 ký tự")]
        [Display(Name = "Mã nhóm SP")]
        [Required(ErrorMessage = "Yêu cầu nhập mã nhóm sản phẩm")]
        [Unique(ErrorMessage = "Mã nhóm sản phẩm đã tồn tại rồi !!", TargetModelType = typeof(EquGroup), TargetPropertyName = "Id")]
        public string Id { get; set; }

        [MaxLength(128, ErrorMessage = "Tên nhóm sản phẩm không quá 128 ký tự")]
        [Display(Name = "Tên nhóm SP")]
        [Required(ErrorMessage = "Yêu cầu nhập tên nhóm sản phẩm")]
        [Unique(ErrorMessage = "Tên nhóm sản phẩm đã tồn tại rồi !!", TargetModelType = typeof(EquGroup), TargetPropertyName = "Name")]
        public string Name { get; set; }
    
        public virtual ICollection<EquTypeVM> EquTypes { get; set; }
    }
}
