//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataVMs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Handover
    {
        public Handover()
        {
            this.HandoverAccs = new HashSet<HandoverAcc>();
        }
    
        public int HandoverID { get; set; }
        public string HandoverNo { get; set; }
        public Nullable<System.DateTime> HandoverDate { get; set; }
        public Nullable<System.DateTime> HandoverReceiveEx { get; set; }
        public Nullable<System.DateTime> HandoverReceiveRe { get; set; }
        public string ReceiveStaffID { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string PerName { get; set; }
        public string Position { get; set; }
        public string PerID { get; set; }
        public string PerPhoneNo { get; set; }
        public Nullable<int> HandoverStatusID { get; set; }
        public string HandoverStaffID { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<HandoverAcc> HandoverAccs { get; set; }
        public virtual HandoverStatu HandoverStatu { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
    }
}
