//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataVMs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Number
    {
        public int ID { get; set; }
        public string RequestNo { get; set; }
        public string BillNo { get; set; }
        public string TestNo { get; set; }
        public string Year { get; set; }
        public string YearFull { get; set; }
        public string TestSysNum { get; set; }
        public string TestAccNum { get; set; }
        public string HandoverNo { get; set; }
        public Nullable<int> DocNoIn { get; set; }
        public Nullable<int> DocNoOut { get; set; }
    }
}
