//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataVMs
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeVM
    {
        public OfficeVM()
        {
            this.DocIns = new HashSet<DocInVM>();
            this.DocOuts = new HashSet<DocOutVM>();
        }
    
        public int OfficeID { get; set; }
        public string OfficeCode { get; set; }
        public string OfficeName { get; set; }
    
        public virtual ICollection<DocInVM> DocIns { get; set; }
        public virtual ICollection<DocOutVM> DocOuts { get; set; }
    }
}
