//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataVMs
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatus
    {
        public OrderStatus()
        {
            this.OrderSts = new HashSet<OrderSt>();
        }
    
        public int OrderStID { get; set; }
        public string OrderStName { get; set; }
    
        public virtual ICollection<OrderSt> OrderSts { get; set; }
    }
}
