//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataVMs
{
    using System;
    using System.Collections.Generic;
    
    public partial class RedBill
    {
        public int RedBillID { get; set; }
        public string RedBillNo { get; set; }
        public Nullable<System.DateTime> RedBillDate { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<float> PriceNonTax { get; set; }
        public Nullable<float> Tax { get; set; }
        public Nullable<float> PriceIncludeTax { get; set; }
        public string PriceInText { get; set; }
        public string Note { get; set; }
        public Nullable<int> Finish { get; set; }
    }
}
