//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataVMs
{
    using Data.DataModels;
    using Data.Extensions;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StandardVM: AuditableVM
    {
        [MaxLength(64, ErrorMessage = "Mã tiêu chuẩn không quá 64 ký tự")]
        [Display(Name = "Mã số")]
        [Required(ErrorMessage = "Yêu cầu nhập mã số tiêu chuẩn")]
        [Unique(ErrorMessage = "Mã số đã tồn tại rồi !!", TargetModelType = typeof(Standard), TargetPropertyName = "Id")]
        public string Id { get; set; }

        [MaxLength(128, ErrorMessage = "Tên tiêu chuẩn không quá 128 ký tự")]
        [Display(Name = "Tên tiêu chuẩn")]
        [Required(ErrorMessage = "Yêu cầu nhập Tên tiêu chuẩn")]
        [Unique(ErrorMessage = "Tên tiêu chuẩn đã tồn tại rồi !!", TargetModelType = typeof(Standard), TargetPropertyName = "Name")]
        public string Name { get; set; }

        [Display(Name = "Mã loại tiêu chuẩn")]
        [Required(ErrorMessage = "Yêu cầu nhập mã loại tiêu chuẩn")]
        public string StdTypeId { get; set; }

        [MaxLength(512, ErrorMessage = "Tóm tăt về tiêu chuẩn không quá 512 ký tự")]
        [Display(Name = "Tóm tăt ")]
        [Required(ErrorMessage = "Yêu cầu nhập Tóm tăt về tiêu chuẩn")]
        public string Abstract { get; set; }

        [MaxLength(256, ErrorMessage = "Tên File tiêu chuẩn không quá 64 ký tự")]
        [Display(Name = "Tên File")]
        [Required(ErrorMessage = "Yêu cầu nhập Tên File tiêu chuẩn")]
        public string FileName { get; set; }

        [Display(Name = "URL")]
        public string URL { get; set; }

        [Display(Name = "Ngày ban hành")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> IssueDate { get; set; }

        [Display(Name = "Ngày hiệu lực")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> ValidDate { get; set; }

        [Display(Name = "VB Giá")]
        public string FeeDoc { get; set; }

        [Display(Name = "Giá ĐK")]
        public int FeePrice { get; set; }

        [Display(Name = "Tên PTN")]
        public string LabID { get; set; }
    
        public virtual StdTypeVM StdType { get; set; }
    }
}
