//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataVMs
{
    using Data.DataModels;
    using Data.Extensions;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StatusVM : AuditableVM
    {
        public StatusVM()
        {
        }
        [MaxLength(16, ErrorMessage = "Mã trạng thái không quá 16 ký tự")]
        [Display(Name = "Mã trạng thái")]
        [Required(ErrorMessage = "Yêu cầu nhập Mã trạng thái")]
        [Unique(ErrorMessage = "Mã trang thái đã tồn tại rồi !!", TargetModelType = typeof(Status), TargetPropertyName = "Id")]
        public string Id { get; set; }

        [MaxLength(256, ErrorMessage = "Tên trạng thái không quá 256 ký tự")]
        [Display(Name = "Tên trạng thái")]
        [Required(ErrorMessage = "Yêu cầu nhập Tên trạng thái")]
        [Unique(ErrorMessage = "Tên trạng thái đã tồn tại rồi !!", TargetModelType = typeof(Status), TargetPropertyName = "Name")]
        public string Name { get; set; }

        [Display(Name = "Các trạng thái có liên kết")]
        public string LinkedIds { get; set; }

        [Display(Name = "Thuộc nhóm")]
        public string Group { get; set; }

        [Display(Name = "Biểu thức lọc")]
        public string Description { get; set; }

        public virtual ICollection<Request> Requests { get; set; }
    }
}
