//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataVMs
{
    using Data.DataModels;
    using Data.Extensions;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class StdTypeVM: AuditableVM
    {

        [MaxLength(16,ErrorMessage = "Tên loại tiêu chuẩn không quá 16 ký tự")]
        [Display(Name = "Ký hiệu loại tiêu chuẩn")]
        [Required(ErrorMessage = "Yêu cầu nhập tên Ký hiệu loại tiêu chuẩn")]
        [Unique(ErrorMessage = "Ký hiệu loại tiêu chuẩn đã tồn tại rồi !!", TargetModelType = typeof(StdType), TargetPropertyName = "Id")]
        public string Id { get; set; }

        [MaxLength(128, ErrorMessage = "Tên loại tiêu chuẩn không quá 128 ký tự")]
        [Display(Name = "Tên loại tiêu chuẩn")]
        [Required(ErrorMessage = "Yêu cầu nhập tên loại tiêu chuẩn")]
        [Unique(ErrorMessage = "Tên loại tiêu chuẩn đã tồn tại rồi !!", TargetModelType = typeof(StdType), TargetPropertyName = "Name")]
        public string Name { get; set; }
        public virtual ICollection<StandardVM> Standards { get; set; }
    }
}
