//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataVMs
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSystem
    {
        public TestSystem()
        {
            this.Calibrations = new HashSet<Calibration>();
            this.TestAccessories = new HashSet<TestAccessory>();
        }
    
        public int TestSysID { get; set; }
        public string TestSysNo { get; set; }
        public string TestSysName { get; set; }
        public string Model { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> MadeYear { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string History { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> FieldID { get; set; }
        public string TestSpec { get; set; }
        public Nullable<int> Valid { get; set; }
        public Nullable<int> Register { get; set; }
    
        public virtual ICollection<Calibration> Calibrations { get; set; }
        public virtual ICollection<TestAccessory> TestAccessories { get; set; }
        public virtual TestField TestField { get; set; }
        public virtual TestSysStatu TestSysStatu { get; set; }
        public virtual TestSystemSource TestSystemSource { get; set; }
    }
}
