//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DataVMs
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestSysStatu
    {
        public TestSysStatu()
        {
            this.HandoverAccs = new HashSet<HandoverAcc>();
            this.TestAccessories = new HashSet<TestAccessory>();
            this.TestSystems = new HashSet<TestSystem>();
        }
    
        public int TestSysStatusID { get; set; }
        public string TestSysStatusName { get; set; }
    
        public virtual ICollection<HandoverAcc> HandoverAccs { get; set; }
        public virtual ICollection<TestAccessory> TestAccessories { get; set; }
        public virtual ICollection<TestSystem> TestSystems { get; set; }
    }
}
